### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by robsonbittencourt** [mechero/code-quality-game#1]
I had an error trying to launch the application. I am not aware with Spring and README configuration part is not very explanatory . Below is the stack. I appreciate if you can help , because I want to start using this game.

`Error starting ApplicationContext. To display the auto-configuration report enabled debug logging (start with --debug)

00:10:13,516 ERROR [org.springframework.boot.SpringApplication] (ServerService Thread Pool -- 66) Application startup failed: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sonarServerConfigurationService' defined in "/home/robson/dev/wildfly-10.0.0.Final/standalone/deployments/code-quality-game.war/WEB-INF/classes/es/macero/cqgame/modules/configuration/service/SonarServerConfigurationService.class": Unsatisfied dependency expressed through constructor argument with index 0 of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao]: : No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:747)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1017)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:120)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:142)
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:89)
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:51)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:184)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1103)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:963)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:811)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:739)
	... 28 more

00:10:13,519 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 66) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./code-quality-game: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./code-quality-game: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sonarServerConfigurationService' defined in "/home/robson/dev/wildfly-10.0.0.Final/standalone/deployments/code-quality-game.war/WEB-INF/classes/es/macero/cqgame/modules/configuration/service/SonarServerConfigurationService.class": Unsatisfied dependency expressed through constructor argument with index 0 of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao]: : No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sonarServerConfigurationService' defined in "/home/robson/dev/wildfly-10.0.0.Final/standalone/deployments/code-quality-game.war/WEB-INF/classes/es/macero/cqgame/modules/configuration/service/SonarServerConfigurationService.class": Unsatisfied dependency expressed through constructor argument with index 0 of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao]: : No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:231)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sonarServerConfigurationService' defined in "/home/robson/dev/wildfly-10.0.0.Final/standalone/deployments/code-quality-game.war/WEB-INF/classes/es/macero/cqgame/modules/configuration/service/SonarServerConfigurationService.class": Unsatisfied dependency expressed through constructor argument with index 0 of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao]: : No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:747)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1017)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:120)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:142)
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:89)
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:51)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:184)
	... 8 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1103)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:963)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:811)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:739)
	... 28 more

00:10:13,526 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "code-quality-game.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./code-quality-game" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./code-quality-game: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sonarServerConfigurationService' defined in \"/home/robson/dev/wildfly-10.0.0.Final/standalone/deployments/code-quality-game.war/WEB-INF/classes/es/macero/cqgame/modules/configuration/service/SonarServerConfigurationService.class\": Unsatisfied dependency expressed through constructor argument with index 0 of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao]: : No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
    Caused by: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sonarServerConfigurationService' defined in \"/home/robson/dev/wildfly-10.0.0.Final/standalone/deployments/code-quality-game.war/WEB-INF/classes/es/macero/cqgame/modules/configuration/service/SonarServerConfigurationService.class\": Unsatisfied dependency expressed through constructor argument with index 0 of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao]: : No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
    Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sonarServerConfigurationService' defined in \"/home/robson/dev/wildfly-10.0.0.Final/standalone/deployments/code-quality-game.war/WEB-INF/classes/es/macero/cqgame/modules/configuration/service/SonarServerConfigurationService.class\": Unsatisfied dependency expressed through constructor argument with index 0 of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao]: : No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
    Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}"}}
00:10:13,570 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 34) WFLYSRV0010: Deployed "code-quality-game.war" (runtime-name : "code-quality-game.war")
00:10:13,572 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./code-quality-game: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./code-quality-game: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sonarServerConfigurationService' defined in "/home/robson/dev/wildfly-10.0.0.Final/standalone/deployments/code-quality-game.war/WEB-INF/classes/es/macero/cqgame/modules/configuration/service/SonarServerConfigurationService.class": Unsatisfied dependency expressed through constructor argument with index 0 of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao]: : No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [es.macero.cqgame.modules.configuration.dao.SonarServerConfigurationDao] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}

00:10:13,775 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
00:10:13,776 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
00:10:13,776 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.0.0.Final (WildFly Core 2.0.10.Final) started (with errors) in 18998ms - Started 449 of 743 services (2 services failed or missing dependencies, 383 services are lazy, passive or on-demand)
00:10:13,814 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-7) WFLYJCA0019: Stopped Driver service with driver-name = code-quality-game.war_org.h2.Driver_1_3
00:10:13,876 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0028: Stopped deployment code-quality-game.war (runtime-name: code-quality-game.war) in 69ms
00:10:13,990 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) WFLYSRV0009: Undeployed "code-quality-game.war" (runtime-name: "code-quality-game.war")
00:10:13,992 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 2) WFLYCTL0183: Service status report
WFLYCTL0184:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."code-quality-game.war".component."com.sun.faces.config.ConfigureListener".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."javax.faces.webapp.FacetTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.ArgumentTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.BindErrorsTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.BindTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.EscapeBodyTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.EvalTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.HtmlEscapeTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.MessageTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.NestedPathTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.ParamTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.ThemeTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.TransformTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.UrlTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.ButtonTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.CheckboxTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.CheckboxesTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.ErrorsTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.FormTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.HiddenInputTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.InputTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.LabelTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.OptionTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.OptionsTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.PasswordInputTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.RadioButtonTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.RadioButtonsTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.SelectTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.deployment.unit."code-quality-game.war".component."org.springframework.web.servlet.tags.form.TextareaTag".START (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
      service jboss.undertow.deployment.default-server.default-host./code-quality-game (missing) dependents: [service jboss.deployment.unit."code-quality-game.war".deploymentCompleteService] 
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./code-quality-game`

**Comment by mechero** [comment]
Hi, thanks for your interest in this project!
I updated the code and now should be fixed. Let me know if you need more help.
