### ISSUE TITLE
Can't start frontend project

### ISSUE THREAD

**Issue by JavaJimFl** [mechero/code-quality-game#8]
Hello,

I didn't have any problem configuring and starting the SonarQube connector as either a WAR file or a Maven goal, but I can't resolve an issue getting the front end to start.  I upgraded npm and node to the latest versions, and created an environment variable called ```Node_ENV``` and set it to ```development```.  (I'm not sure about the environment variable though, as I'm not a JS developer).

Could you please point me in the right direction?  the debug log is below:

Regards,

Jim

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Bob\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.8.0
3 info using node@v8.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle code-quality-game@1.0.0~prestart: code-quality-game@1.0.0
6 info lifecycle code-quality-game@1.0.0~start: code-quality-game@1.0.0
7 verbose lifecycle code-quality-game@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle code-quality-game@1.0.0~start: PATH: C:\Users\Bob\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\code-quality-game\frontend\node_modules\.bin;C:\Oracle\Software\bin;C:\Program Files\avs\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\IBM\ITM\bin;C:\IBM\ITM\TMAITM6;C:\IBM\ITM\InstallITM;D:\apache-maven-3.5.0\bin;C:\Program Files\Java\jdk1.8.0_131;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Program Files\Java\jdk1.8.0_131\jre\bin;C:\Program Files\Git\cmdC:\ProgramData\Oracle\Java\javapath;C:\Oracle\Software\bin;C:\Program Files\avs\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\IBM\ITM\bin;C:\IBM\ITM\TMAITM6;C:\IBM\ITM\InstallITM;C:\apache-maven-3.5.0\bin;C:\Program Files\Java\jdk1.8.0_131;C:\Program Files\Java\jdk1.8.0_131\lib;C:\Program Files\Java\jdk1.8.0_131\jre\bin;Program Files\nodejs\;C:\Program Files\Git\cmd;%M2;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;S:\proddlls\pbnt;Z:.;Y:.;X:.;S:\proddlls\sql\bin;S:\proddlls\sql\dll;C:\Users\Bob\AppData\Roaming\npm
9 verbose lifecycle code-quality-game@1.0.0~start: CWD: D:\code-quality-game\frontend
10 silly lifecycle code-quality-game@1.0.0~start: Args: [ '/d /s /c', 'tsc && concurrently "tsc -w" "lite-server" ' ]
11 silly lifecycle code-quality-game@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle code-quality-game@1.0.0~start: Failed to exec start script
13 verbose stack Error: code-quality-game@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Bob\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Bob\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid code-quality-game@1.0.0
15 verbose cwd D:\code-quality-game\frontend
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bob\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error code-quality-game@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 1
23 error Failed at the code-quality-game@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by JavaJimFl** [comment]
I discovered that if I ran ```npm install``` after cloning the repository, the dependencies would be updated correctly and the front end would start without issues.  Problem solved!

**Comment by mechero** [comment]
Great! Sorry I've been a bit disconnected for a while. 
I'll add that to the README file, it's not there and it's a required step, thanks for the comment+close.

**Comment by JavaJimFl** [comment]
You're welcome.  Thanks for taking this on.
